services:
  bot:
    build: .
    container_name: oreo-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    networks:
      - bot_net

networks:
  bot_net:
    name: discord_bot_net
    external: true
